'use client';

import { useFinanceStore } from '@/lib/finance/store/finance-store';
import { useState } from 'react';
import { Plus, Calendar, AlertTriangle, ShieldCheck, CheckCircle2, Clock, Pencil, Trash2, X, ChevronRight } from 'lucide-react';
import { FundingCategory, FundingStatus, FundingNeed } from '@/lib/finance/types';

export default function FundingPage() {
  const store = useFinanceStore();

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    title: '',
    category: 'large_expense' as FundingCategory,
    amount: '',
    neededByDate: '',
    status: 'planned' as FundingStatus,
  });


  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.title || !formData.amount || !formData.neededByDate) return;
    if (editingId) {
      store.updateFundingNeed(editingId, { title: formData.title, category: formData.category, amount: Number(formData.amount), neededByDate: formData.neededByDate, status: formData.status, updatedAt: new Date().toISOString() });
    } else {
      store.addFundingNeed({ id: crypto.randomUUID(), title: formData.title, category: formData.category, amount: Number(formData.amount), neededByDate: formData.neededByDate, status: formData.status, source: 'manual', autoGenerated: false, fundingPlan: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
    }
    resetForm();
  };

  const handleEdit = (need: FundingNeed) => {
    setFormData({ title: need.title, category: need.category, amount: need.amount.toString(), neededByDate: need.neededByDate, status: need.status });
    setEditingId(need.id);
    setIsFormOpen(true);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleDelete = (id: string) => {
    if (confirm('이 자금 계획을 삭제하시겠습니까?')) {
      store.deleteFundingNeed(id);
      if (editingId === id) resetForm();
    }
  };

  const resetForm = () => {
    setFormData({ title: '', category: 'large_expense', amount: '', neededByDate: '', status: 'planned' });
    setEditingId(null);
    setIsFormOpen(false);
  };

  const formatKRW = (amount: number) =>
    new Intl.NumberFormat('ko-KR', { style: 'currency', currency: 'KRW' }).format(amount);

  const sortedNeeds = [...store.fundingNeeds].sort((a, b) => new Date(a.neededByDate).getTime() - new Date(b.neededByDate).getTime());
  const liquidNetWorth = store.getLiquidNetWorth();
  const today = new Date();

  const categoryLabel = (c: FundingCategory) =>
    ({ auction_deposit: '경매 보증금', auction_settlement: '경락 잔금', card_payment: '카드결제', large_expense: '목돈 지출', auction_eviction: '명도 비용', other: '기타' })[c] ?? c;

  const statusConfig = (s: FundingStatus) => ({
    planned: { label: '계획됨', icon: <Clock size={11} />, cls: 'text-gray-500 bg-gray-100 border-gray-200' },
    fundraising: { label: '조달 중', icon: <AlertTriangle size={11} />, cls: 'text-amber-600 bg-amber-50 border-amber-200' },
    completed: { label: '완료', icon: <CheckCircle2 size={11} />, cls: 'text-emerald-600 bg-emerald-50 border-emerald-200' },
    cancelled: { label: '취소됨', icon: <X size={11} />, cls: 'text-gray-400 bg-gray-100 border-gray-200' },
  })[s];

  return (
    <div className="space-y-5 max-w-[1400px] mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 tracking-tight">자금 계획</h1>
          <p className="text-gray-400 text-sm mt-0.5">자금 수요 및 조달 시나리오 관리</p>
        </div>
        <button
          onClick={() => (isFormOpen ? resetForm() : setIsFormOpen(true))}
          className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md transition-all shadow-sm ${
            isFormOpen
              ? 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50'
              : 'bg-amber-500 text-white hover:bg-amber-600'
          }`}
        >
          {isFormOpen ? <X size={12} /> : <Plus size={12} />}
          {isFormOpen ? '취소' : '새 계획 수립'}
        </button>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <div className="bg-white rounded-xl border border-gray-200 px-5 py-4 flex items-center justify-between shadow-sm">
          <div className="flex items-center gap-2">
            <ShieldCheck className="text-blue-600" size={16} />
            <p className="text-xs text-gray-500 font-medium">가용 유동성</p>
          </div>
          <p className="text-lg font-bold text-blue-600 tabular-nums">{formatKRW(liquidNetWorth)}</p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 px-5 py-4 flex items-center justify-between shadow-sm">
          <div className="flex items-center gap-2">
            <AlertTriangle className="text-amber-500" size={16} />
            <p className="text-xs text-gray-500 font-medium">조달 중인 건</p>
          </div>
          <p className="text-lg font-bold text-amber-600">{sortedNeeds.filter(n => n.status === 'fundraising').length}건</p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 px-5 py-4 flex items-center justify-between shadow-sm">
          <div className="flex items-center gap-2">
            <Calendar className="text-gray-500" size={16} />
            <p className="text-xs text-gray-500 font-medium">총 계획 건</p>
          </div>
          <p className="text-lg font-bold text-gray-800">{sortedNeeds.length}건</p>
        </div>
      </div>

      {isFormOpen && (
        <div className="bg-white rounded-xl border border-amber-200 p-5 shadow-sm">
          <h3 className="text-sm font-semibold text-gray-900 mb-4">{editingId ? '자금 계획 수정' : '새 자금 수요 등록'}</h3>
          <form onSubmit={handleSubmit} className="space-y-3">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
              <div className="space-y-1.5 md:col-span-2">
                <label className="text-xs font-medium text-gray-600">항목명</label>
                <input type="text" required className="w-full bg-gray-50 border border-gray-200 px-3 py-2 rounded-lg text-sm text-gray-900 outline-none focus:border-amber-400 focus:bg-white transition-colors" placeholder="예: 나경빌라 입찰보증금" value={formData.title} onChange={e => setFormData({ ...formData, title: e.target.value })} />
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-gray-600">분류</label>
                <select className="w-full bg-gray-50 border border-gray-200 px-3 py-2 rounded-lg text-sm text-gray-900 outline-none" value={formData.category} onChange={e => setFormData({ ...formData, category: e.target.value as FundingCategory })}>
                  <option value="auction_deposit">경매 보증금</option>
                  <option value="auction_settlement">경락 잔금</option>
                  <option value="large_expense">목돈 지출</option>
                  <option value="other">기타</option>
                </select>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-gray-600">상태</label>
                <select className="w-full bg-gray-50 border border-gray-200 px-3 py-2 rounded-lg text-sm text-gray-900 outline-none" value={formData.status} onChange={e => setFormData({ ...formData, status: e.target.value as FundingStatus })}>
                  <option value="planned">계획됨</option>
                  <option value="fundraising">조달 중</option>
                  <option value="completed">조달 완료</option>
                </select>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-3 items-end">
              <div className="space-y-1.5 md:col-span-2">
                <label className="text-xs font-medium text-gray-600">필요 금액 (원)</label>
                <input type="number" required className="w-full bg-gray-50 border border-gray-200 px-3 py-2 rounded-lg text-sm text-gray-900 outline-none focus:border-amber-400 focus:bg-white transition-colors" placeholder="0" value={formData.amount} onChange={e => setFormData({ ...formData, amount: e.target.value })} />
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-gray-600">필요 시기</label>
                <input type="date" required className="w-full bg-gray-50 border border-gray-200 px-3 py-2 rounded-lg text-sm text-gray-900 outline-none focus:border-amber-400 focus:bg-white transition-colors" value={formData.neededByDate} onChange={e => setFormData({ ...formData, neededByDate: e.target.value })} />
              </div>
              <div className="flex items-end">
                <button type="submit" className="w-full bg-amber-500 text-white px-4 py-2 rounded-lg text-xs font-semibold hover:bg-amber-600 transition-colors">
                  {editingId ? '수정 저장' : '저장'}
                </button>
              </div>
            </div>
          </form>
        </div>
      )}

      {/* Timeline */}
      <div className="space-y-3">
        <h2 className="text-sm font-semibold text-gray-700 flex items-center gap-2">
          <span className="w-0.5 h-4 bg-amber-500 rounded-full" />
          자금 수요 타임라인
        </h2>

        {sortedNeeds.length === 0 ? (
          <div className="bg-white rounded-xl border border-dashed border-gray-300 p-10 text-center shadow-sm">
            <p className="text-xs text-gray-400">등록된 자금 계획이 없습니다.</p>
            <button onClick={() => setIsFormOpen(true)} className="mt-3 text-xs text-amber-600 hover:text-amber-700 flex items-center gap-1 mx-auto font-medium">
              <Plus size={12} /> 첫 계획 수립하기
            </button>
          </div>
        ) : (
          <div className="space-y-2">
            {sortedNeeds.map((need) => {
              const shortfall = need.amount - liquidNetWorth;
              const isShortfall = shortfall > 0 && need.status !== 'completed';
              const dateObj = new Date(need.neededByDate);
              const daysDiff = Math.ceil((dateObj.getTime() - today.getTime()) / (1000 * 3600 * 24));
              const sc = statusConfig(need.status);

              return (
                <div key={need.id} className={`bg-white rounded-xl border p-5 transition-all group shadow-sm ${isShortfall ? 'border-amber-200 hover:border-amber-300' : 'border-gray-200 hover:border-gray-300'}`}>
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap mb-1.5">
                        <span className={`inline-flex items-center gap-1 text-[11px] font-medium px-2 py-0.5 rounded border ${need.category === 'auction_deposit' || need.category === 'auction_settlement' ? 'bg-amber-50 text-amber-600 border-amber-200' : 'bg-gray-100 text-gray-500 border-gray-200'}`}>
                          {categoryLabel(need.category)}
                        </span>
                        <span className={`inline-flex items-center gap-1 text-[11px] font-medium px-2 py-0.5 rounded border ${sc?.cls}`}>
                          {sc?.icon}{sc?.label}
                        </span>
                      </div>
                      <h3 className="text-sm font-semibold text-gray-900">{need.title}</h3>
                      <div className="flex items-center gap-2 mt-1.5 text-xs text-gray-400">
                        <Calendar size={11} />
                        <span>{dateObj.toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
                        <span className={`px-1.5 py-0.5 rounded text-[11px] font-semibold ${daysDiff < 0 ? 'bg-rose-50 text-rose-500' : daysDiff <= 7 ? 'bg-amber-50 text-amber-600' : 'bg-gray-100 text-gray-500'}`}>
                          {daysDiff < 0 ? `D+${Math.abs(daysDiff)}` : daysDiff === 0 ? 'D-Day' : `D-${daysDiff}`}
                        </span>
                      </div>
                    </div>

                    <div className="flex items-center gap-6 shrink-0">
                      <div className="text-right">
                        <p className="text-xs text-gray-400 mb-1">필요 금액</p>
                        <p className="text-base font-bold text-gray-900 tabular-nums">{formatKRW(need.amount)}</p>
                      </div>

                      {isShortfall && (
                        <div className="text-right border-l border-gray-200 pl-6">
                          <p className="text-[11px] text-rose-500 mb-1 flex items-center justify-end gap-1">
                            <AlertTriangle size={10} /> 부족 예상
                          </p>
                          <p className="text-base font-bold text-rose-500 tabular-nums">-{formatKRW(shortfall)}</p>
                        </div>
                      )}

                      {need.status !== 'completed' && (
                        <div className="text-right border-l border-gray-200 pl-6">
                          <p className="text-xs text-gray-400 mb-1">가용 유동성</p>
                          <p className="text-base font-bold text-blue-600 tabular-nums">{formatKRW(liquidNetWorth)}</p>
                        </div>
                      )}

                      <div className="flex flex-col gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button onClick={() => handleEdit(need)} className="p-1 text-gray-400 hover:text-blue-500 transition-colors"><Pencil size={14} /></button>
                        <button onClick={() => handleDelete(need.id)} className="p-1 text-gray-400 hover:text-rose-500 transition-colors"><Trash2 size={14} /></button>
                      </div>
                    </div>
                  </div>

                  {isShortfall && (
                    <div className="mt-3 pt-3 border-t border-gray-100 flex items-center justify-between">
                      <p className="text-xs text-gray-400">조달 방법: 주식 매도 / 대출 / 적금 해지</p>
                      <a href="/assets" className="text-xs text-amber-600 hover:text-amber-700 flex items-center gap-0.5 transition-colors font-medium">
                        자산 확인 <ChevronRight size={10} />
                      </a>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
