export type AssetCategory = 'stock' | 'cash' | 'illiquid' | 'real_estate';
export type LiabilityType = 'bank_loan' | 'credit_line' | 'auction_settlement_loan' | 'other';
export type ExpenseCategory = 'card_payment' | 'utility' | 'insurance' | 'subscription' | 'management_fee' | 'seasonal_gift' | 'interest' | 'other';
export type IncomeType = 'salary' | 'bonus' | 'interest' | 'dividend' | 'rent' | 'other';
export type FundingCategory = 'card_payment' | 'large_expense' | 'auction_deposit' | 'auction_settlement' | 'auction_eviction' | 'other';
export type FundingStatus = 'planned' | 'fundraising' | 'completed' | 'cancelled';
export type FundingMethod = 'cash' | 'stock_sale' | 'loan' | 'savings_withdrawal' | 'other';

export type CashAccountType = 'securities' | 'bank';

export interface CashAsset {
  id: string;
  name: string;
  institution: string;
  accountType: CashAccountType;
  amount: number;
  updatedAt: string;
}

export interface IlliquidAsset {
  id: string;
  name: string;
  amount: number;
  isStatic: boolean;
  updatedAt: string;
}

export type RealEstateType = 'apartment' | 'land' | 'building' | 'commercial' | 'other';
export type RealEstateValuation = 'official' | 'market';

export interface RealEstateAsset {
  id: string;
  name: string;
  address?: string;
  realEstateType: RealEstateType;
  source: 'auctionflow' | 'manual';
  auctionCaseId?: string;
  officialPrice: number;
  marketPrice: number;
  valuationType: RealEstateValuation;
  estimatedValue: number;
  acquisitionCost: number;
  updatedAt: string;
}

export interface Liability {
  id: string;
  name: string;
  lenderType: LiabilityType;
  source: 'auctionflow' | 'manual';
  auctionCaseId?: string;
  lender: string;
  principal: number;
  interestRate: number;
  monthlyInterest: number;
  dueDay?: number;
  maturityDate: string | null;
}

export interface FixedExpense {
  id: string;
  name: string;
  category: ExpenseCategory;
  cardIssuer?: string;
  recipientName?: string;
  amount: number;
  cycle: 'monthly' | 'quarterly' | 'yearly' | 'seasonal';
  nextDueDate: string;
  dueDay?: number;
  linkedLiabilityId?: string;
}

export interface Income {
  id: string;
  name: string;
  earnerName?: string;
  incomeType: IncomeType;
  source: 'manual' | 'auctionflow_rent' | 'stockmind_dividend';
  amount: number;
  cycle: 'monthly' | 'irregular';
  receivedDate?: string;
}

export interface FundingPlanItem {
  method: FundingMethod;
  amount: number;
  detail?: string;
  estimatedRate?: number;
}

export interface FundingNeed {
  id: string;
  title: string;
  category: FundingCategory;
  amount: number;
  neededByDate: string;
  status: FundingStatus;
  source: 'auctionflow' | 'manual';
  auctionCaseId?: string;
  autoGenerated: boolean;
  fundingPlan: FundingPlanItem[];
  createdAt: string;
  updatedAt: string;
}

export interface AssetSnapshot {
  id: string;
  snapshotDate: string;
  stockValue: number;
  stockCash: number;
  cashAssets: CashAsset[];
  illiquidAssets: IlliquidAsset[];
  realEstateAssets: RealEstateAsset[];
  totalAssets: number;
  liquidNetWorth: number;
}

// ─── 가계부 (M3) ─────────────────────────────────────────────────────────────

export type TransactionType = 'expense' | 'income' | 'transfer';
export type PaymentMethod = 'cash' | 'check_card' | 'credit_card' | 'bank_transfer';

// 기존 고정 카테고리를 기본값으로 유지하되, 확장을 위해 string 허용 고려
export type MainCategory = string;

export interface CategoryInfo {
  name: string;
  sub: string[];
  color: string;
  incomeOk: boolean;
}

export const DEFAULT_CATEGORY_META: Record<string, CategoryInfo> = {
  식비:    { name: '식비',    sub: ['외식', '식재료', '편의점', '카페'],           color: 'amber',   incomeOk: false },
  교통:    { name: '교통',    sub: ['대중교통', '주유', '주차', '톨비'],           color: 'blue',    incomeOk: false },
  통신:    { name: '통신',    sub: ['휴대폰', '인터넷', 'OTT 구독'],               color: 'violet',  incomeOk: false },
  의료:    { name: '의료',    sub: ['병원', '약국', '건강기능식품'],                color: 'rose',    incomeOk: false },
  교육:    { name: '교육',    sub: ['자녀학원', '자기계발', '도서'],                color: 'green',   incomeOk: false },
  문화:    { name: '문화',    sub: ['영화/공연', '여행', '취미'],                   color: 'pink',    incomeOk: false },
  경조사:  { name: '경조사',  sub: ['결혼/조의', '명절', '생일'],                   color: 'yellow',  incomeOk: false },
  보험:    { name: '보험',    sub: ['생명보험', '실손', '자동차보험'],              color: 'slate',   incomeOk: false },
  대출상환: { name: '대출상환', sub: ['원금', '이자'],                               color: 'red',     incomeOk: false },
  주거관리: { name: '주거관리', sub: ['관리비', '공과금', '수선'],                   color: 'teal',    incomeOk: false },
  용돈:    { name: '용돈',    sub: ['본인', '자녀', '부모'],                        color: 'indigo',  incomeOk: false },
  임대수입: { name: '임대수입', sub: ['월세'],                                       color: 'emerald', incomeOk: true  },
  급여:    { name: '급여',    sub: ['본봉', '상여', '부업'],                        color: 'emerald', incomeOk: true  },
  기타:    { name: '기타',    sub: [],                                              color: 'gray',    incomeOk: true  },
};

export const DEFAULT_EXPENSE_CATEGORIES = [
  '식비', '교통', '통신', '의료', '교육', '문화', '경조사',
  '보험', '대출상환', '주거관리', '용돈', '기타',
];
export const DEFAULT_INCOME_CATEGORIES = ['급여', '임대수입', '기타'];

export interface LedgerSettings {
  categories: CategoryInfo[];
  cardIssuers: string[];
  users: string[];
}

export interface Transaction {
  id: string;
  date: string; // YYYY-MM-DD
  amount: number;
  type: TransactionType;
  category: MainCategory;
  subCategory?: string;
  paymentMethod: PaymentMethod;
  cardIssuer?: string;
  memo?: string;
  isFixed: boolean;
  user?: string;
  createdAt: string;
}

export interface Budget {
  id: string;
  category: MainCategory;
  monthlyLimit: number;
}

// ─── 순자산 히스토리 (M8) ───────────────────────────────────────────────────

export interface NetWorthSnapshot {
  id: string;
  snapshotDate: string; // YYYY-MM-01
  totalAssets: number;
  totalLiabilities: number;
  liquidNetWorth: number;
  totalNetWorth: number;
  breakdown: {
    cash: number;
    stock: number;
    realEstate: number;
    illiquid: number;
  };
}
